# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37b945cf90bf59ab6d79d11d7669976a929d21e521b19d32b4f2d37b525b6f066539dc7cc09e64750c9d6e1e2f0642dd0f4d8fe7715315e540fbd6caa1cfcfed

test:
  secret_key_base: e190191398cf82c4c2f6beeffbd78ba4e52f3cdf819d11a962624838835969956cc540b51c685e5c37298ebd0ee303a86e401aeca4e432663edb2dfd16ad9ea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
